components:
  parameters:
    Authorization:
      in: header
      name: Authorization
      schema:
        type: string
  schemas:
    Headers:
      properties:
        Authorization:
          type: string
      type: object
    NamespaceRequest:
      properties:
        code:
          type: string
        name:
          type: string
      type: object
    NamespaceResponse:
      properties:
        name:
          type: string
      type: object
    model.NamespaceResponse:
      properties:
        name:
          type: string
      type: object
  securitySchemes:
    AuthorizationHeader:
      type: APIKey
info:
  contact:
    email: shaun@infinityservers.co.uk
    name: Infinity Servers
  description: API for Infinity Servers panel for interactions to kubernetes.
  license:
    name: MIT
    url: https://en.wikipedia.org/wiki/MIT_License
  termsOfService: https://www.infinityservers.co.uk/terms
  title: Infinity Servers API
  version: 1.0.0
openapi: 3.0.0
paths:
  /namespace:
    get:
      description: ' Get a list of namespaces.'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NamespaceResponse'
          description: The response from the kubernetes cluster
      summary: List namespaces
      tags:
      - namespace
  /namespace/{namespace}:
    delete:
      description: ' Delete a namespace'
      parameters:
      - description: The namespace name
        in: path
        name: namespace
        required: true
        schema:
          description: The namespace name
          format: string
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NamespaceResponse'
          description: The response from the kubernetes cluster
      summary: Delete namespace
      tags:
      - namespace
    get:
      description: ' Get a namespace'
      parameters:
      - description: The namespace name
        in: path
        name: namespace
        required: true
        schema:
          description: The namespace name
          format: string
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NamespaceResponse'
          description: The response from the kubernetes cluster
      summary: Get namespace
      tags:
      - namespace
    post:
      description: ' Create a namespace'
      parameters:
      - description: The namespace name
        in: path
        name: namespace
        required: true
        schema:
          description: The namespace name
          format: string
          type: string
      responses:
        "201":
          description: Namespace created
        "409":
          description: Already exists
      summary: Create namespace
      tags:
      - namespace
    put:
      description: ' Update a namespace'
      parameters:
      - description: The namespace name
        in: path
        name: namespace
        required: true
        schema:
          description: The namespace name
          format: string
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NamespaceRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NamespaceResponse'
          description: The response from the kubernetes cluster
      summary: Update namespace
      tags:
      - namespace
security:
- AuthorizationHeader:
  - read
  - write
servers:
- description: Default Server URL
  url: /
