/*
 * Infinity Servers API
 *
 * This is a simple API for K8
 *
 * API version: 1.0.0
 * Contact: support@infinityservers.co.uk
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/Infinityservers/GoK8/1.0.0/",
		Index,
	},

	Route{
		"CreateDeployment",
		strings.ToUpper("Post"),
		"/Infinityservers/GoK8/1.0.0/deployment/{deployment}",
		CreateDeployment,
	},

	Route{
		"DeleteDeployment",
		strings.ToUpper("Delete"),
		"/Infinityservers/GoK8/1.0.0/deployment/{deployment}",
		DeleteDeployment,
	},

	Route{
		"GetDeployment",
		strings.ToUpper("Get"),
		"/Infinityservers/GoK8/1.0.0/deployment/{deployment}",
		GetDeployment,
	},

	Route{
		"ListDeployments",
		strings.ToUpper("Get"),
		"/Infinityservers/GoK8/1.0.0/deployment",
		ListDeployments,
	},

	Route{
		"CreateNamespace",
		strings.ToUpper("Post"),
		"/Infinityservers/GoK8/1.0.0/namespace/{name}",
		CreateNamespace,
	},

	Route{
		"DeleteNamespace",
		strings.ToUpper("Delete"),
		"/Infinityservers/GoK8/1.0.0/namespace/{name}",
		DeleteNamespace,
	},

	Route{
		"GetNamespace",
		strings.ToUpper("Get"),
		"/Infinityservers/GoK8/1.0.0/namespace/{name}",
		GetNamespace,
	},

	Route{
		"ListNamespaces",
		strings.ToUpper("Get"),
		"/Infinityservers/GoK8/1.0.0/namespace",
		ListNamespaces,
	},
}
